### ISSUE TITLE
This library is cool, can all the files and folders be added to a single directory?

### ISSUE THREAD

**Issue by repollo** [ohn0/youtube-livechat-scraper#15]
As the title reads, right now when you pip install this library to a `venv` it results in its directories being all over the place with other library directories, if it were to have its own directory one can go and modify a specific thing directly instead of having to scramble through multiple directories.

<img width="298" alt="Screenshot 2023-09-24 at 5 25 42 AM" src="https://github.com/ohn0/youtube-livechat-scraper/assets/2671466/eacc4a50-a692-4d78-9c67-2e80a379c7bb">

**Comment by ohn0** [comment]
didnt realize this even happened, I'll take a look and see how to clean it up, thanks.

**Comment by ohn0** [comment]
try now from PyPi, all the modules are inside livechat_scraper now

**Comment by repollo** [comment]
NIce! Closed!
