### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'build_message'

### ISSUE THREAD

**Issue by louissullivan4** [ohn0/youtube-livechat-scraper#26]
Ran example.py with this video url: https://www.youtube.com//watch?v=vL8FTN9O4ms
Error outputted by script:
```
C:\dir>example.py
Beginning livechat scraping
scraping completed
the payload above has a message type that is not currently being tracked.
Traceback (most recent call last):
  File "C:\dirl\example.py", line 25, in <module>
    test_scraper_output("https://www.youtube.com//watch?v=vL8FTN9O4ms")
  File "C:\dir\example.py", line 16, in test_scraper_output
    scraper.write_to_file(sCons.OUTPUT_JSON, "testJson_"+scraper.output_filename)
  File "C:\dir\livechat_scraper\scrapers\livechat_scraper.py", line 131, in write_to_file
    generator.generate(self.output_messages(), write_type)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dir\livechat_scraper\scrapers\livechat_scraper.py", line 121, in output_messages
    message.build_message()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'build_message'
```

Sorry tried to debug but I believe there is a new message type that isn't being processed by the script that I cannot find. Any help on this would be great. I wouldn't mind a temp fix that just skips message types that cause this crash. Thanks !

**Comment by louissullivan4** [comment]
Just got the payload it failed on :)
```
{
    "clickTrackingParams": "CAEQl98BIhMIgpXHr8ycgwMVHiQGAB2AHA7H",
    "addChatItemAction": {
        "item": {
            "liveChatPlaceholderItemRenderer": {
                "id": "ChwKGkNNWFcwb2VnallNREZhZlF3Z1FkZFFrRXZB",
                "timestampUsec": "1702499282387958"
            }
        },
        "clientId": "CMXW0oegjYMDFafQwgQddQkEvA"
    }
}
```

**Comment by ohn0** [comment]
Cool thanks, I can add it in later today if you still need it.

**Comment by louissullivan4** [comment]
would be great ! added a weird fix but I am still wrapping my head around the code :)

**Comment by louissullivan4** [comment]
Actually have a quick question for you! Do you think it would be possible for me to fork and adapt this code to also grab the details of the stream that the chat is being grabbed from such as Title, Views and Date ?

**Comment by ohn0** [comment]
Alright should be fixed for that message type and stream now.

I'd have to look into the initial response to see if those fields exist, if they do, adding them should not be an issue, I'll check in a bit.

**Comment by louissullivan4** [comment]
Great it works now thanks !

Yes sorry should have done this in a different issue!
